[2025-02-17T18:10:46.833+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-17T18:10:46.970+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tax_etl_pipeline.run_tax_etl scheduled__2025-02-17T18:00:00+00:00 [queued]>
[2025-02-17T18:10:47.028+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tax_etl_pipeline.run_tax_etl scheduled__2025-02-17T18:00:00+00:00 [queued]>
[2025-02-17T18:10:47.029+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-17T18:10:47.093+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): run_tax_etl> on 2025-02-17 18:00:00+00:00
[2025-02-17T18:10:47.152+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'tax_etl_pipeline', 'run_tax_etl', 'scheduled__2025-02-17T18:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/tax_etl_dag.py', '--cfg-path', '/tmp/tmpomaz7jle']
[2025-02-17T18:10:47.168+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask run_tax_etl
[2025-02-17T18:10:47.186+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=183) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-17T18:10:47.195+0000] {standard_task_runner.py:72} INFO - Started process 184 to run task
[2025-02-17T18:10:47.576+0000] {task_command.py:467} INFO - Running <TaskInstance: tax_etl_pipeline.run_tax_etl scheduled__2025-02-17T18:00:00+00:00 [running]> on host 7b3a2f7430fa
[2025-02-17T18:10:49.368+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tax_etl_pipeline' AIRFLOW_CTX_TASK_ID='run_tax_etl' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-17T18:00:00+00:00'
[2025-02-17T18:10:49.378+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-17T18:10:50.054+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-02-17T18:10:50.065+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark-master:7077 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --verbose /opt/***/etl/main.py
[2025-02-17T18:10:50.362+0000] {spark_submit.py:641} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-02-17T18:10:50.366+0000] {spark_submit.py:641} INFO - JAVA_HOME is not set
[2025-02-17T18:10:50.389+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-master:7077 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --verbose /opt/***/etl/main.py. Error code is: 1.
[2025-02-17T18:10:50.439+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=tax_etl_pipeline, task_id=run_tax_etl, run_id=scheduled__2025-02-17T18:00:00+00:00, execution_date=20250217T180000, start_date=20250217T181046, end_date=20250217T181050
[2025-02-17T18:10:50.531+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-17T18:10:50.532+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 2 for task run_tax_etl (Cannot execute: spark-submit --master spark-master:7077 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --verbose /opt/***/etl/main.py. Error code is: 1.; 184)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark-master:7077 --executor-cores 2 --executor-memory 2g --driver-memory 1g --name arrow-spark --verbose /opt/***/etl/main.py. Error code is: 1.
[2025-02-17T18:10:50.588+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-17T18:10:50.637+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-17T18:10:50.645+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
